// Package echo detects HTTP entry points registered via the Echo v4 framework
// (github.com/labstack/echo/v4). It covers both *echo.Echo and *echo.Group
// receivers, plus the generic Add(method, path, handler) variant and
// interface-dispatch registration (oapi-codegen echoRouter pattern).
//
// Register this detector by importing the package for its side effects:
//
//	import _ "sauron-eye/internal/graph/entrypoints/frameworks/echo"
package echo

import (
	"go/token"
	"go/types"
	"strings"

	"golang.org/x/tools/go/ssa"

	"sauron-eye/internal/graph/entrypoints"
)

func init() {
	entrypoints.RegisterHTTPDetector(&detector{})
}

type detector struct{}

func (d *detector) Name() string { return "echo" }

// namedPatterns covers the named-method registration calls on both *Echo and
// *Group. Signature: receiver.METHOD(path string, handler HandlerFunc, middleware ...MiddlewareFunc)
// SSA Args: [0]=receiver [1]=path [2]=handler [3+]=variadic middleware
var namedPatterns = map[string]entrypoints.RoutePattern{
	// *echo.Echo
	"(*github.com/labstack/echo/v4.Echo).GET":     {Method: "GET", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).POST":    {Method: "POST", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).PUT":     {Method: "PUT", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).DELETE":  {Method: "DELETE", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).PATCH":   {Method: "PATCH", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).OPTIONS": {Method: "OPTIONS", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).HEAD":    {Method: "HEAD", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Echo).Any":     {Method: "ANY", PathArgIdx: 1, HandlerArgIdx: 2},

	// *echo.Group
	"(*github.com/labstack/echo/v4.Group).GET":     {Method: "GET", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).POST":    {Method: "POST", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).PUT":     {Method: "PUT", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).DELETE":  {Method: "DELETE", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).PATCH":   {Method: "PATCH", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).OPTIONS": {Method: "OPTIONS", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).HEAD":    {Method: "HEAD", PathArgIdx: 1, HandlerArgIdx: 2},
	"(*github.com/labstack/echo/v4.Group).Any":     {Method: "ANY", PathArgIdx: 1, HandlerArgIdx: 2},
}

// addCallee are the qualified names for the generic Add variant.
// Signature: receiver.Add(method, path string, handler HandlerFunc, middleware ...MiddlewareFunc)
// SSA Args: [0]=receiver [1]=method [2]=path [3]=handler [4+]=variadic middleware
var addCallee = map[string]struct{}{
	"(*github.com/labstack/echo/v4.Echo).Add":  {},
	"(*github.com/labstack/echo/v4.Group).Add": {},
}

func (d *detector) Detect(allFuncs []*ssa.Function, fset *token.FileSet, _ string) []entrypoints.DetectedEntry {
	entries := entrypoints.DetectByRoutePatterns(allFuncs, fset, namedPatterns, "echo")
	entries = append(entries, detectAdd(allFuncs, fset)...)
	entries = append(entries, detectInvokeMode(allFuncs, fset)...)
	return entries
}

// invokeHTTPMethods is the set of method names that indicate HTTP route
// registration on an echo-like interface (oapi-codegen, custom wrappers, etc.).
var invokeHTTPMethods = map[string]string{
	"GET":     "GET",
	"POST":    "POST",
	"PUT":     "PUT",
	"DELETE":  "DELETE",
	"PATCH":   "PATCH",
	"OPTIONS": "OPTIONS",
	"HEAD":    "HEAD",
	"CONNECT": "CONNECT",
	"TRACE":   "TRACE",
	"Any":     "ANY",
}

// detectInvokeMode handles route registrations where the router is an
// interface value (e.g. the echoRouter interface generated by oapi-codegen).
// In SSA invoke mode the receiver is not in Args, so PathArgIdx=0 and
// HandlerArgIdx=1.
//
// Matching criterion: invoke call whose method name is an HTTP verb AND whose
// second parameter type string contains "labstack/echo" — this avoids
// false-positives from unrelated interfaces that happen to have a GET method.
func detectInvokeMode(allFuncs []*ssa.Function, fset *token.FileSet) []entrypoints.DetectedEntry {
	var entries []entrypoints.DetectedEntry

	for _, fn := range allFuncs {
		for _, block := range fn.Blocks {
			for _, instr := range block.Instrs {
				callInstr, ok := instr.(ssa.CallInstruction)
				if !ok {
					continue
				}
				call := callInstr.Common()
				if !call.IsInvoke() {
					continue
				}

				httpMethod, matched := invokeHTTPMethods[call.Method.Name()]
				if !matched {
					continue
				}

				// Confirm this is an echo-related interface by checking that the
				// second parameter type is echo.HandlerFunc (or a type whose
				// string representation mentions labstack/echo).
				sig, ok := call.Method.Type().(*types.Signature)
				if !ok || sig.Params().Len() < 2 {
					continue
				}
				if !strings.Contains(sig.Params().At(1).Type().String(), "labstack/echo") {
					continue
				}

				// In invoke mode: Args = [path, handler, ...middleware]
				if len(call.Args) < 2 {
					continue
				}

				handler := entrypoints.ExtractFunction(call.Args[1])
				if handler == nil {
					continue
				}

				path := normalizePath(entrypoints.ExtractStringBestEffort(call.Args[0]))

				file := ""
				line := 0
				if pos := instr.Pos(); pos.IsValid() {
					p := fset.Position(pos)
					file = p.Filename
					line = p.Line
				}

				entries = append(entries, entrypoints.DetectedEntry{
					Source:    "http",
					Method:    httpMethod,
					Path:      path,
					Framework: "echo",
					Handler:   handler,
					File:      file,
					Line:      line,
				})
			}
		}
	}

	return entries
}

// detectAdd handles the generic Add(method, path, handler, ...middleware) form.
// It tries to extract the HTTP method from the first string argument; if the
// argument is not a constant it falls back to "ANY".
func detectAdd(allFuncs []*ssa.Function, fset *token.FileSet) []entrypoints.DetectedEntry {
	var entries []entrypoints.DetectedEntry

	for _, fn := range allFuncs {
		for _, block := range fn.Blocks {
			for _, instr := range block.Instrs {
				callInstr, ok := instr.(ssa.CallInstruction)
				if !ok {
					continue
				}
				call := callInstr.Common()
				if _, matched := addCallee[entrypoints.CalleeQualName(call)]; !matched {
					continue
				}

				args := call.Args
				// Need at least receiver + method + path + handler = 4 args
				if len(args) < 4 {
					continue
				}

				handler := entrypoints.ExtractFunction(args[3])
				if handler == nil {
					continue
				}

				method := entrypoints.ExtractStringConst(args[1])
				if method == "" {
					method = "ANY"
				} else {
					method = strings.ToUpper(method)
				}

				path := entrypoints.ExtractStringConst(args[2])

				file := ""
				line := 0
				if pos := instr.Pos(); pos.IsValid() {
					p := fset.Position(pos)
					file = p.Filename
					line = p.Line
				}

				entries = append(entries, entrypoints.DetectedEntry{
					Source:    "http",
					Method:    method,
					Path:      path,
					Framework: "echo",
					Handler:   handler,
					File:      file,
					Line:      line,
				})
			}
		}
	}

	return entries
}

// normalizePath cleans up paths produced by ExtractStringBestEffort.
// When the base URL is a runtime variable, the extractor returns "*/rest/of/path".
// The leading "*" is a placeholder for the unknown prefix; stripping it leaves
// a clean absolute path that starts with "/".
func normalizePath(path string) string {
	if strings.HasPrefix(path, "*/") {
		return path[1:]
	}
	return path
}
