package entrypoints

import (
	"go/token"
	"go/types"
	"strings"

	"golang.org/x/tools/go/ssa"
)

// grpcRegisterPattern is the qualified name of grpc.Server.RegisterService.
const grpcRegisterPattern = "(*google.golang.org/grpc.Server).RegisterService"

// FindGRPCHandlers scans for gRPC service registrations and extracts handler methods.
func FindGRPCHandlers(prog *ssa.Program, allFuncs []*ssa.Function, fset *token.FileSet) []DetectedEntry {
	var entries []DetectedEntry

	for _, fn := range allFuncs {
		for _, block := range fn.Blocks {
			for _, instr := range block.Instrs {
				callInstr, ok := instr.(ssa.CallInstruction)
				if !ok {
					continue
				}

				call := callInstr.Common()
				qualName := CalleeQualName(call)

				// Match both:
				//   static call:    (*grpc.Server).RegisterService  — old proto-gen style
				//   interface call: grpc.ServiceRegistrar.RegisterService — new proto-gen style (grpc v1.32+)
				isStaticMatch := qualName == grpcRegisterPattern
				isIfaceMatch := call.IsInvoke() &&
					call.Method.Name() == "RegisterService" &&
					strings.Contains(call.Value.Type().String(), "grpc")
				if !isStaticMatch && !isIfaceMatch {
					continue
				}

				// For static calls Args = [receiver, desc, impl]; for interface dispatch Args = [desc, impl].
				// In both cases impl is the last argument.
				args := call.Args
				minArgs := 3
				if isIfaceMatch {
					minArgs = 2
				}
				if len(args) < minArgs {
					continue
				}

						// impl is the concrete service implementation
				impl := args[len(args)-1]

				// Walk the pointer chain to get the underlying named type.
				// When impl is interface-typed (e.g. the srv parameter inside a generated
				// RegisterXxxServer wrapper), extractNamedType returns nil. In that case
				// we search all callers of this wrapper to find the concrete type(s)
				// actually passed in — they arrive wrapped in a MakeInterface node.
				namedType := extractNamedType(impl.Type())
				if namedType == nil {
					for _, t := range resolveImplTypesFromCallers(fn, len(args)-1, allFuncs) {
						entries = append(entries, grpcHandlersForType(prog, t, fset)...)
					}
					continue
				}

				entries = append(entries, grpcHandlersForType(prog, namedType, fset)...)
			}
		}
	}

	return entries
}

// extractNamedType unwraps pointer types to find the underlying *types.Named.
func extractNamedType(t types.Type) *types.Named {
	switch v := t.(type) {
	case *types.Named:
		return v
	case *types.Pointer:
		if named, ok := v.Elem().(*types.Named); ok {
			return named
		}
	}
	return nil
}

// grpcHandlersForType returns DetectedEntry items for all methods on namedType
// that match the gRPC handler signature (context.Context, *Proto) (*Proto, error).
func grpcHandlersForType(prog *ssa.Program, namedType *types.Named, fset *token.FileSet) []DetectedEntry {
	var entries []DetectedEntry
	mset := types.NewMethodSet(types.NewPointer(namedType))
	for i := 0; i < mset.Len(); i++ {
		sel := mset.At(i)
		methodObj, ok := sel.Obj().(*types.Func)
		if !ok {
			continue
		}
		if !looksLikeGRPCHandler(methodObj) {
			continue
		}
		ssaFn := prog.FuncValue(methodObj)
		if ssaFn == nil {
			continue
		}
		file, line := funcPosition(ssaFn, fset)
		entries = append(entries, DetectedEntry{
			Source:  "grpc",
			Method:  methodObj.Name(),
			Handler: ssaFn,
			File:    file,
			Line:    line,
		})
	}
	return entries
}

// resolveImplTypesFromCallers finds all callers of fn that pass a concrete type
// as the argIdx-th argument and returns those named types. This handles the
// RegisterXxxServer pattern generated by protoc-gen-go-grpc where the service
// impl is passed as an interface (XxxServer), hiding the concrete type from the
// scanner. At the call site the concrete value is visible as a MakeInterface node.
func resolveImplTypesFromCallers(fn *ssa.Function, argIdx int, allFuncs []*ssa.Function) []*types.Named {
	var result []*types.Named
	seen := map[*types.Named]bool{}
	for _, caller := range allFuncs {
		for _, block := range caller.Blocks {
			for _, instr := range block.Instrs {
				callInstr, ok := instr.(ssa.CallInstruction)
				if !ok {
					continue
				}
				call := callInstr.Common()
				if call.StaticCallee() != fn {
					continue
				}
				if argIdx >= len(call.Args) {
					continue
				}
				arg := call.Args[argIdx]
				// Interface conversions are explicit in SSA as MakeInterface nodes;
				// unwrap to get the underlying concrete value.
				if mi, ok := arg.(*ssa.MakeInterface); ok {
					arg = mi.X
				}
				if named := extractNamedType(arg.Type()); named != nil && !seen[named] {
					seen[named] = true
					result = append(result, named)
				}
			}
		}
	}
	return result
}

// looksLikeGRPCHandler checks if the function signature resembles a gRPC handler.
// gRPC handlers have signature: func(ctx context.Context, req *Proto) (*Proto, error)
func looksLikeGRPCHandler(fn *types.Func) bool {
	sig, ok := fn.Type().(*types.Signature)
	if !ok {
		return false
	}
	params := sig.Params()
	results := sig.Results()

	// Must have 2 params and 2 results
	if params.Len() != 2 || results.Len() != 2 {
		return false
	}

	// First param should be context.Context
	firstParam := params.At(0).Type().String()
	if !strings.Contains(firstParam, "context.Context") {
		return false
	}

	// Last result should be error
	lastResult := results.At(1).Type().String()
	return lastResult == "error"
}
